service: scheduler-service

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    MONGODB_URI: ${env:MONGODB_URI} # MongoDB 연결 정보
    QUEUE_URL:
      Ref: ScheduleQueue # SQS Queue URL을 환경 변수로 전달
    CUSTOM_AWS_REGION: ap-northeast-2

functions:
  # API 비즈니스 로직 처리 핸들러
  schedulerApi:
    handler: src/handlers/scheduler.handler
    events:
      - httpApi:
          path: /schedules
          method: post
      - httpApi:
          path: /schedules
          method: get

  # SQS 메시지 처리 핸들러
  sqsWorker:
    handler: src/handlers/worker.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ScheduleQueue, Arn] # SQS Queue ARN 참조
          batchSize: 5

resources:
  Resources:
    # Primary SQS Queue
    ScheduleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: schedule-queue
        RedrivePolicy: # Dead Letter Queue 설정
          deadLetterTargetArn:
            Fn::GetAtt: [ScheduleDLQ, Arn] # DLQ ARN 참조
          maxReceiveCount: 5 # 최대 재시도 횟수

    # Dead Letter Queue (DLQ)
    ScheduleDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: schedule-dlq
